apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodedemo
  name: nodedemo
  namespace: jose-iriarte
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodedemo
  template:
    metadata:
      labels:
        app: nodedemo
    spec:
      containers:
        - name: node-demo
          image: docker.io/jgenso/node-demo:0.0.1
          imagePullPolicy: Always  
          env:
           - name: MONGO_USERNAME
             valueFrom:
               secretKeyRef:
                 name: mongodb-secret
                 key: username_root
           - name: MONGO_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: mongodb-secret
                 key: password_root
           - name: MONGO_HOST
             valueFrom:
               configMapKeyRef: 
                 name: node-map
                 key: mongoHost
           - name: MONGO_DB
             valueFrom: 
               configMapKeyRef:
                 name: node-map
                 key: mongoDB
