apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-service
  name: mongodb-svc
  namespace: jose-iriarte
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 32032
  selector:
    app: nodedemo
  type: NodePort
status:
  loadBalancer: {}
